// react-app/src/components/CarEditRow.js
import React from 'react';

import { useForm } from '../hooks/useForm';

export const CarEditRow = (props) => {

  const [
    carForm,
    change
  ] = useForm({
    make: props.car.make,
    model: props.car.model,
    year: props.car.year,
    color: props.car.color,
    price: props.car.price,
  });

  const saveCar = () => {
    props.onSaveCar({
      ...carForm,
      id: props.car.id,
    });
  };

  return (
    <tr>
      <td>{props.car.id}</td>
      <td><input type="text" id="edit-make-input" name="make" value={carForm.make} onChange={change} /></td>
      <td><input type="text" id="edit-model-input" name="model" value={carForm.model} onChange={change} /></td>
      <td><input type="text" id="edit-year-input" name="year" value={carForm.year} onChange={change} /></td>
      <td><input type="text" id="edit-color-input" name="color" value={carForm.color} onChange={change} /></td>
      <td><input type="text" id="edit-price-input" name="price" value={carForm.price} onChange={change} /></td>
      <td>
        <button type="button" onClick={saveCar}>Save</button>
        <button type="button" onClick={props.onCancelCar}>Cancel</button>
      </td>
    </tr>
  );

};

// angular-app/src/app/car-tool/components/car-edit-row/car-edit-row.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

import { Car } from '../../models/Car';

@Component({
  selector: 'tr.app-car-edit-row',
  templateUrl: './car-edit-row.component.html',
  styleUrls: ['./car-edit-row.component.css']
})
export class CarEditRowComponent implements OnInit {

  @Input()
  car: Car;

  @Output()
  saveCar = new EventEmitter<Car>();

  @Output()
  cancelCar = new EventEmitter<void>();

  // state, value can be changed
  carForm: FormGroup;

  constructor(private fb: FormBuilder) { }

  ngOnInit(): void {
    this.carForm = this.fb.group({
      make: this.car.make,
      model: this.car.model,
      year: this.car.year,
      color: this.car.color,
      price: this.car.price,
    });
  }

  doSaveCar(): void {
    this.saveCar.emit({
      ...this.carForm.value,
      id: this.car.id,
    });
  }

}

<ng-container [formGroup]="carForm">
  <td>{{car.id}}</td>
  <td><input type="text" formControlName="make"></td>
  <td><input type="text" formControlName="model"></td>
  <td><input type="number" formControlName="year"></td>
  <td><input type="text" formControlName="color"></td>
  <td><input type="number" formControlName="price"></td>
  <td>
    <button type="button" (click)="doSaveCar()">Save</button>
    <button type="button" (click)="cancelCar.emit()">Cancel</button>
  </td>
</ng-container>
