// angular-app/src/app/car-tool/components/car-table/car-table.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { Car } from '../../models/Car';

@Component({
  selector: 'app-car-table',
  templateUrl: './car-table.component.html',
  styleUrls: ['./car-table.component.css']
})
export class CarTableComponent implements OnInit {

  @Input()
  cars: Car[] = [];

  constructor() { }

  ngOnInit(): void {
  }

}

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Color</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <tr class="app-car-view-row" *ngFor="let car of cars" [car]="car"></tr>
  </tbody>
</table>

// react-app/src/components/CarTable.js
import React from 'react';

import { CarViewRow } from './CarViewRow';

export const CarTable = (props) => {

  return (
    <table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Make</th>
          <th>Model</th>
          <th>Year</th>
          <th>Color</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        {props.cars.map(car => <CarViewRow key={car.id} car={car} />)}
      </tbody>
    </table>
  );

}
