// react-app/src/components/CarViewRow.js
import React from 'react';

export const CarViewRow = ({
  car,
  onEditCar: editCar,
  onDeleteCar: deleteCar,
}) => {

  return (
    <tr>
      <td>{car.id}</td>
      <td>{car.make}</td>
      <td>{car.model}</td>
      <td>{car.year}</td>
      <td>{car.color}</td>
      <td>{car.price}</td>
      <td>
        <button type="button" onClick={() => editCar(car.id)}>Edit</button>
        <button type="button" onClick={() => deleteCar(car.id)}>Delete</button>
      </td>
    </tr>
  );

};

// angular-app/src/app/car-tool/components/car-view-row/car-view-row.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

import { Car } from '../../models/Car';

@Component({
  selector: 'tr.app-car-view-row',
  templateUrl: './car-view-row.component.html',
  styleUrls: ['./car-view-row.component.css']
})
export class CarViewRowComponent implements OnInit {

  @Input() // props, value immutable
  car: Car;

  @Output()
  editCar = new EventEmitter<number>();

  @Output()
  deleteCar = new EventEmitter<number>();

  constructor() { }

  ngOnInit(): void {
  }

}

<td>{{car.id}}</td>
<td>{{car.make}}</td>
<td>{{car.model}}</td>
<td>{{car.year}}</td>
<td>{{car.color}}</td>
<td>{{car.price}}</td>
<td>
  <button type="button" (click)="editCar.emit(car.id)">
    Edit
  </button>
  <button type="button" (click)="deleteCar.emit(car.id)">
    Delete
  </button>
</td>
